### ISSUE TITLE
Does anyone have a recipe for a React app?

### ISSUE THREAD

**Issue by punkpeye** [huozhi/sugar-high#102]
I would love to adopt this in https://glama.ai instead of using the heavy `react-syntax-highlighter`.

```tsx
<pre dangerouslySetInnerHTML={{ __html: highlight(code) }} />;
```

I think I can just `dangerouslySetInnerHTML`, but wanted to double check.

**Comment by huozhi** [comment]
Yep that's the correct usage! Feel free to PR to the READ for this use case 🙌
