### ISSUE TITLE
There is not a right style in doc website?

### ISSUE THREAD

**Issue by Yukiniro** [huozhi/sugar-high#48]
![截屏2022-05-17 23 30 13](https://user-images.githubusercontent.com/21242087/168850548-667c0d38-560e-4c74-afc2-67ee01450321.png)

I set the `height: max-content` for `code` tag could resolve it. But I'm not sure that's the best solution for solving the problem in `codice`.

**Comment by huozhi** [comment]
Thanks for reporting! I'm rewriting the editor part as well, will update soon.
