### ISSUE TITLE
feature request: line(s) highlighting and adding file name for code block

### ISSUE THREAD

**Issue by hampak** [huozhi/sugar-high#92]
Hello, thank you for making such a lightweight syntax highlighter for JSX.

I'd like to propose a feature request where we can highlight specific lines in the block of code and also give the code block a name (file name).

For example, people who use "shiki" can do this very easily by specifying like this:

```
```jsx {5} title="hello.js"
// code goes here
```

This will highlight the 5th line in the code block and will also give the code block the title "hello.js" which will appear either below or above the block (which can be customizable).

Thank you :D

**Comment by huozhi** [comment]
Hi @hampak, you can use CSS `.sh__line:nth-child()` to get the line and select the certain line of the code for now, and customize with your own style.

The markdown example is integrated with markdown rendere, I'm not sure if that's feature on the renderer side. curious are you using sugar-high as markdown highlighter?

**Comment by hampak** [comment]
Hi, @huozhi! Thank you for the reply.

I'll note the method you've mentioned regarding the line highlighting.

For your question: Yes, I'm using it as a markdown highlighter for my personal blog. I'm using MDX.

**Comment by huozhi** [comment]
Could you share a bit more how you're using it with MDX, I'd love to help support it if it's possible

**Comment by hampak** [comment]
Sure,

I'm making a blog where I'm using MDX (with the frontmatter and the actual content).

I'm using **MDXRemote** from `next-mdx-remote/rsc` for the utilities it provides. This is the code where I implement sugar high:

```tsx
function Code({ children, ...props }) {
  const codeHTML = highlight(children)
  return (
    <code dangerouslySetInnerHTML={{ __html: codeHTML }} {...props} />
  )
}

let components = {
  code: Code
}

export const MDX = (props) => {

  return (
    <>
      <MDXRemote
        {...props}
        components={{ ...components, ...(props.components || {}) }}
      />
    </>
  )
}
```
This is how my MDX file looks like:
![image](https://github.com/huozhi/sugar-high/assets/85291626/ef3637ad-3c44-4b1f-b146-078bd533da4f)

**Comment by huozhi** [comment]
Will you get the **line number** or file **title** that get highlighted through props?

For `title` I think it should be sth outside of code, so need sth wrapping the `<code>` from outside.

```jsx
<div>
  <div>{tiltle}</div>
  <code /> 
</div>
```

Regarding to **line number** I'm thinking if we can inject some dynamic style there before `<code>` tag? Or are you having global. Where did you get the line number props?

**Comment by hampak** [comment]
**Where did you get the line number props?** -> hmm... only thing I can say for sure is that I'm inputting the line numbers like this:

```mdx
``` mdx {2-4}
// content goes here
```

This creates a custom css style which I can later style it for myself like this:

```css
.prose [data-highlighted-line] {
  /* goes here */
}
```

**Comment by nikhilsnayak** [comment]
@hampak @huozhi Here is the code to add the request feature https://github.com/nikhilsnayak/nikhilsnayak.dev/pull/181

**Comment by huozhi** [comment]
I'll explore this as extension in another repo probably, as it's more like the md/mdx integration for sugar-high

**Comment by HamzaAmar** [comment]
@huozhi I suggest adding plus and minus signs before each line when highlighting data. When a plus sign is used, a data attribute like data-type='positive' should be added to the line, similar to what GitHub does when we see git diff.

**Comment by huozhi** [comment]
I published a remark highlight library of sugar-high [remark-sugar-high](https://github.com/huozhi/remark-sugar-high), feel free to try it out! I'm using it on my blog right now.

That one is a good place to add features like highlight on certain line or decorate code frame, and sugar-high itself can be kept as a core library to focus on parse and render the code to html.

I'll close this one fore now

**Comment by huozhi** [comment]
Line highlight example is live!

https://remark-sugar-high.vercel.app/
